### PR TITLE
Add TestRandom to testkit (#623)

### PR DESCRIPTION
**Pull request by jupposessho**
I'd like to generalise the check* functions in the spec but could not do it. Any idea?

### CODE REVIEW

**Comment by jdegoes** [comment]
@jupposessho Awesome work!

Here's an idea to generalize `check`:

```scala
def checkWith[A](data: Data, expected: List[A])(f: Random.Service[Any] => UIO[A]) = 
   unsafeRun(
    for {
      ref   <- Ref.make(data)
      testr = IO.succeed(TestRandom(ref)
      make1 = f(testr)
      nexts <- IO.foreach(0 to expected.length)(_ => make1)
    } yield nexts must_=== expected
   )
```

**Comment by jupposessho** [comment]
Thanks @jdegoes, updated the spec.

**Comment by jupposessho** [comment]
Copy that. What is the most elegant(or good enough) way to notify the user if the test data break the contract? What do you suggest?

**Comment by LGLO** [comment]
@jupposessho WDYT about making private constructor and having `apply` or other constructor method in companion object that returns `ZIO[Any, InvalidData, TestConsole]`?

**Comment by jdegoes** [comment]
@jupposessho @LGLO I don't think we need to validate user data, just ensure the "test data" we supply out of the box doesn't violate the contract.

**Comment by jupposessho** [comment]
So only the defaults should be changed for the Double, Float and Gaussian?

If we want to validate, it could be a solution:
`sealed abstract case class TestRandom private(ref: Ref[TestRandom.Data]) extends Random.Service[Any]`

`def fromData(data: Data): ZIO[Any, InvalidData, TestRandom] =
    // validation IO.fail... 
    for {
      ref        <- Ref.make(data)
      testRandom <- IO.succeed(new TestRandom(ref) {})
    } yield testRandom`

Thanks, @LGLO for the idea.
But I can agree with @jdegoes, if the user want "invalid" data, why not :)

**Comment by jdegoes** [comment]
> So only the defaults should be changed for the Double, Float and Gaussian?

Yes, that's what I'd do, just make sure our "out of the box" test data satisfies the contract.

**Comment by jupposessho** [comment]
I've changed the defaults

**Comment by jdegoes** [comment]
@jupposessho Super! Ready to merge as soon as Travis CI passes. Thanks for your work on this!

**Comment by jupposessho** [comment]
The pleasure was mine.

**Comment by jdegoes** [comment]
giphy

**Pull request merged**
