### PR TITLE
Auto-publish microsite

### LINKED ISSUE #209: Automate microsite generation

### PR DESCRIPTION
**Pull request by NeQuissimus**
Closes #209 

- Initialized `gh-pages` branch
- Added a deploy key
- Named build stages
- Publish microsite for tag pushes

### CODE REVIEW

**Comment by NeQuissimus** [comment]
I moved the microsite into this repo (onto the `gh-pages` branch) because that works just as well and is supported by the microsite plugin as a publishing target (it is able to publish into another repo but not a folder)

**Comment by NeQuissimus** [comment]
@jdegoes broke this :-P

**Comment by jdegoes** [comment]
@NeQuissimus Technically JRuby failing to download broke master. I just added more fuel to the fire. 🔥 😆

**Comment by NeQuissimus** [comment]
That was a corrupted Travis cache, it was not being downloaded.

**Comment by jdegoes** [comment]
@sideeffffect Is this good to go?

**Comment by sideeffffect** [comment]
@jdegoes let's see how it will work in development
can you also try pushing a new tag on `master` after merging this?

**Comment by jdegoes** [comment]
@sideeffffect Yes, I'll push a new tag after merging this.

**Comment by jdegoes** [comment]
@sideeffffect @NeQuissimus Unfortunately, we still have a failure to build 2.11 artifacts:

<https://travis-ci.org/scalaz/scalaz-zio/builds/419819557>

**Comment by NeQuissimus** [comment]
@jdegoes It's the stupid Travis caches. I don't know why they keep corrupting.

**Comment by jdegoes** [comment]
@sideeffffect @NeQuissimus 

More failures in deploying based on tags:

<https://travis-ci.org/scalaz/scalaz-zio/builds/420181286>

**Pull request merged**
