### PR TITLE
WIP Re-add support for Scala 2.13

### PR DESCRIPTION
**Pull request by denisgarci**
This is a first attempt at https://github.com/scalaz/scalaz-zio/issues/732.
A few dependencies haven't yet been published:
* cats  https://github.com/typelevel/cats/pull/2783
* akka https://github.com/akka/akka/issues/26691

Also I get the following error when running `coreJVM/test`:
```
[error] /Users/denisgarcia/dev/github/scalaz-zio/core/jvm/src/test/scala/scalaz/zio/RTSSpec.scala:1082:25: object interruptible is not a member of package scalaz.zio.blocking
[error]       fiber <- blocking.interruptible { start.set(()); Thread.sleep(Long.MaxValue) }.ensuring(done.set(true)).fork
[error]                         ^
[error] /Users/denisgarcia/dev/github/scalaz-zio/core/jvm/src/test/scala/scalaz/zio/RTSSpec.scala:1068:16: object blockingExecutor is not a member of package scalaz.zio.blocking
[error]       blocking.blockingExecutor.map(_.metrics.get.workersCount)
[error]                ^
[error] /Users/denisgarcia/dev/github/scalaz-zio/core/jvm/src/test/scala/scalaz/zio/RTSSpec.scala:1071:28: object blocking is not a member of package scalaz.zio.blocking
[error] did you mean Blocking?
[error]       thread1  <- blocking.blocking(IO.effectTotal(Thread.currentThread()))
[error]                            ^
[error] three errors found
```
I think it has to do with package object but I'm not sure how to fix it.

### CODE REVIEW

**Comment by jdegoes** [comment]
@denisgarci Cats would hold up publishing for cats-interop. The other ones should work. Is it possible to publish 2.13 for everything but cats-interop?

I can help fix that error.

**Comment by denisgarci** [comment]
@jdegoes Thanks for the feedback. I managed to make `coreJVM` test pass on my local branch! 
To fix the `blocking` package object issue I removed the different specific 2.11 and 2.12 implementation and used the 2.11 package object (no inheritance) for all  3 versions.
Not sure if that's the best way to do it. Package object inheritance will be deprecated in 2.14 https://github.com/scala/scala/pull/7857.
One of the problem I'm facing is that there are a lot of deprecation in `scala.collection` that makes some changes not backward compatible. What's the recommended approach? Copy the code in different `2.11_2.12` /  `2.13` folder or maybe create a small collection utility wrapper?

**Comment by jdegoes** [comment]
@denisgarci 

> To fix the blocking package object issue I removed the different specific 2.11 and 2.12 implementation and used the 2.11 package object (no inheritance) for all 3 versions.

Arg. Not super happy about that. What if you change `package object` to just `object`? Does that make the errors go away?

> Copy the code in different 2.11_2.12 / 2.13 folder or maybe create a small collection utility wrapper?

A small collection utility wrapper would work best! Then the core code will be common. 

Also, it's possible there are already enough overlapping methods we can get it compiling without a common utility wrapper.

**Comment by jdegoes** [comment]
@denisgarci If you run `fmt`, it will fix the linting error. Then I'd add 2.13 to the Travis file to get it building on Travis too.

**Comment by denisgarci** [comment]
So I've pushed all the 2.13 only changes with comments. I couldn't make the `blocking` package object work. It currently lives in `2.12/` folder. Should I rename it to `2.12+/`?

**Comment by jdegoes** [comment]
@denisgarci Can you tell me the error? I'd be happy to help you with that.

I'd love to get this pull request merged in for RC5 (coming this week).

**Comment by denisgarci** [comment]
I don't have access to a computer this weekend. I'll be able to work on it next week though.
My biggest problem right is method that have been deprecated for a a specific Scala version.
For example `. lines` (2.11 & 2.12) vs `. linesIterator` (2.12+ only). Or `.enqueue` vs `.enqueueAll`.

**Comment by jdegoes** [comment]
@denisgarci Please let me know if you need any help with this!

**Comment by denisgarci** [comment]
Closing for now see https://github.com/scalaz/scalaz-zio/issues/732#issuecomment-496974673

**Pull request closed without merging**
