### PR TITLE
+rts Add RejectedExecutionHandler configuration support for RTS.

### PR DESCRIPTION
**Pull request by hepin1989**
RTS should provide a way to configure the underlying threadPool.

### CODE REVIEW

**Comment by jdegoes** [comment]
@hepin1989 Making this configurable makes sense, however, the `saneSafe` rejected execution handler always tries to execute the `Runnable`, which may lead to some surprising results (not that a rejection execution won't, anyway). What do you think about unbundling these changes?

**Comment by hepin1989** [comment]
@jdegoes Thanks for review.
What I expected here is that providing a way to shutdown the `RTS` gracefully,make sure all the submitted tasks been run. The default abort policy will cause problem in production and easy to forget how to gracefully shutdown a `RTS`, when that happens, we may lose some mession cridical tasks.

A better way may be: 1) add a `gracefullyShutdown` method to `RTS` trait and user could call it to first shutdown the `RTS` ,2) make sure we registerred a shutdown hook, and make sure the `RST` will be shutdown gracefully when there is a shutdown or redeploy triggered by auto deploy system.

So the main reason I think is prodovide a way to gracefully online and offline a cridical system which is built around `IO` and its underlying `RTS`.

**Comment by jdegoes** [comment]
@hepin1989 

> What I expected here is that providing a way to shut down the RTS gracefully, make sure all the submitted tasks been run. The default abort policy will cause a problem in production and easy to forget how to gracefully shutdown a RTS, when that happens, we may lose some mission-critical tasks.

You are right. We definitely need to fix this problem.

> A better way may be: 1) add a gracefullyShutdown method to RTS trait and user could call it to first shutdown the RTS, 2) make sure we registered a shutdown hook, and make sure the RST will be shut down gracefully when there is a shutdown or redeploy triggered by automatic deploy system.

In `App`, a shutdown hook is added. Where you thinking more there?

I think we do need `gracefullyShutdown`, and to make this part of `ExitCode` in `App`. See discussion on #356. 

Do you think a good, safe version of `App` is sufficient? i.e. one that waits until the tasks are run, adds the shutdown hook, etc.

**Comment by hepin1989** [comment]
@jdegoes 

>Do you think a good, safe version of App is sufficient? i.e. one that waits until the tasks are run, adds the shutdown hook, etc.

No, but it makes things easier. In a real in production online system, especially in a distributed system, we need first switch out the online inbound communications by the infrastructure and then process all the ongoing works, finally let the infrastructure know that we have done, after that, it will then start to totally bring our App down.

So a good implementation needs both from ZIO and infrastructure support.

**Comment by RaasAhsan** [comment]
I've brought it up before, but I think we're going down the wrong path if we're trying to guarantee the completion of tasks, and not fibers. ZIO code operates on fibers and doesn't deal with individual `Runnable` tasks. Given that many ZIO combinators and the RTS (via its cooperative multitasking mechanism) non-transparently insert an asynchronous boundary, you have no guarantee as to whether a fiber will ever complete on shutdown.

Also, the default thread pool is the default because its what we believe is the best default choice for a thread pool. If the user doesn't want the default thread pool, they will override it. We should avoid giving users the ability to customize a thread pool via the RTS interface because:
- they can just change it themselves
- if they change it, the overridable options don't make any sense
- it probably won't make sense to have for #36

**Comment by hepin1989** [comment]
@RaasAhsan Yes, a user could override it, but what I suggested here is that the default is not the right one, do you have any logging if there is a rejection happening? no, you see, that's a problem.

**Comment by jdegoes** [comment]
I opened #412 so we can discuss what needs to be done there.

**Comment by hepin1989** [comment]
Okay

**Pull request closed without merging**
