### PR TITLE
Add Queue#poll

### PR DESCRIPTION
**Pull request by ioleo**
Add `Queue#poll` helper method returning `UIO[Option[A]]` with the first item in the queue if it exists.

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Looks good! Can you also add it to the doc? https://github.com/scalaz/scalaz-zio/blob/master/microsite/src/main/tut/datatypes/queue.md

**Comment by jdegoes** [comment]
@ioleo Superb! Love that it makes it consistent with `Promise`, `Fiber`, etc.

**Comment by ioleo** [comment]
@ghostdogpr added `poll` description to microsite.

**Comment by ioleo** [comment]
@jdegoes I believe its ready to be merged now.

**Comment by ghostdogpr** [comment]
@ioleo Thanks for the contribution, this is merged!

**Pull request merged**
