### PR TITLE
shut down rts after tests

### PR DESCRIPTION
**Pull request by jdegoes**

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Not sure it will help solving the issue, but `ZioWithFs2Spec` and `catzSpec` are not using `AbstractRTSSpec` so their RTS still doesn't get explicitly stopped.

**Comment by jdegoes** [comment]
@ghostdogpr I think that's the problem. I'm not sure how to solve it yet.

**Comment by regiskuckaertz** [comment]
In all failing builds, `RTSSpec` does not run, perhaps because a previous test suite does not end properly?

I had a hunch that could be related to `io.run` not forking anymore, as it's then that the behaviour started happening, so I reverted the change [here](https://github.com/scalaz/scalaz-zio/pull/372/commits/7329b51f5a5fc04d55cd12223b568ba6122f1158) and my build passed. Now the only difference I can think of is that forking creates a clean stack.

[Trying now](https://github.com/scalaz/scalaz-zio/pull/372/commits/ef2d5857a8149ba73bb435c497a71e262a398275) to see if calling `unwindStack(true)` in the `Tags.Fail` case solves the problem too.

**Comment by jdegoes** [comment]
@regiskuckaertz I see that a few tests in `RTSSpec` are not passing, but rather timing out, which confusingly, Specs2 does not report as a failure. Likely some of these failures imply timeouts in other tests not being wrapped with `upTo` timeout combinator. So probably what's happening is a broken test is not completing.

**Pull request merged**
