### PR TITLE
Cross-build to 2.13.0-M5

### PR DESCRIPTION
**Pull request by NeQuissimus**
- [X] Build with 2.13.0-M5
- [X] Remove 2.11 (even Spark is 2.12 now...)
- [X] TomasMikula/pascal#5 (removed)
- [ ] Monix for 2.13.0-M5 (monix/monix#786)
- [X] Scalacheck-shapeless for 2.13.0-M5 (https://github.com/typelevel/cats-effect/blob/2418893487e3a48739eb7787fc93477cd5f59a40/build.sbt#L40) (alexarchambault/scalacheck-shapeless#97)

### CODE REVIEW

**Comment by jdegoes** [comment]
@NeQuissimus Yes, please! Also to get ZIO on the community build we definitely have to remove Pascal (should also remove anything else that isn't used while we're at it).

How soon can you complete this? 🙏  😄

**Comment by NeQuissimus** [comment]
@jdegoes Pascal is unused? This would be done if the mentioned dependencies existed...

**Comment by NeQuissimus** [comment]
I added `sbt-explicit-dependencies` to detect unused dependencies.
It has a little bit trouble with Scala.JS and JMH but works well now.

**Comment by NeQuissimus** [comment]
Looks like Monix is going to be a bit of work (I linked a ticket above)
I have yet to look at the scalacheck-shapeless library

**Comment by jdegoes** [comment]
@NeQuissimus Maybe we could ship this much of it and finish the rest in a followup PR?

**Comment by NeQuissimus** [comment]
@jdegoes Of course, but you'll have build failures on `master`...

**Comment by NeQuissimus** [comment]
Figured out how to build the cats interop against a snapshot for `scalacheck-shapeless`.

**Comment by LGLO** [comment]
I think it's worth taking a look here: https://typelevel.org/blog/2019/01/30/cats-ecosystem-community-survey-results.html and read about dropping 2.11. But if we are the ones going to sacrifice half of community, few more per cents doesn't really matter 😉

**Comment by NeQuissimus** [comment]
@jdegoes It did help this PR but I put it back. Hopefully, this build should pass...

**Comment by jdegoes** [comment]
@NeQuissimus It's actually failing to compile on 2.11 due to a wrongly inferred type; the 2.13 failure looks like a flaky test.

**Comment by NeQuissimus** [comment]
@jdegoes `Either` is one of those APIs that has changed quite a bit between 2.11 and 2.13... Should be fine now.

**Pull request merged**
