### PR TITLE
Switch from tut to mdoc #687

### PR DESCRIPTION
**Pull request by Dan-M**
Replaces `tut` with `mdoc` for the `microsite`.

### CODE REVIEW

**Comment by NeQuissimus** [comment]
LGTM, I assume the site still looks fine, I have not built it

**Comment by jdegoes** [comment]
@Dan-M Thank you for this! 

Does the microsite build & look fine???

**Comment by jdegoes** [comment]
@Dan-M There are a few `reactive-streams` examples to update. Then, assuming you've built the microsite & it looks fine, we'll get this merged!

I'm really looking forward to the improved experience working with `mdoc`, and the improved build times (I hope).

**Comment by NeQuissimus** [comment]
The build has a ton of warnings, are those OK to ignore?

**Comment by Dan-M** [comment]
@jdegoes I guess these examples were without `tut:` before already or I merged them from upstream after running the migration script. I will update these examples as well.
I've build the microsite locally and it looks "as before".

I will look into the warnings as well. But I guess they are not new.

One thing that you might want to have a special look at is variable naming. I tried to infer them from the context. But I'm not sure they are all right.

**Comment by jdegoes** [comment]
@Dan-M Sounds good! Just one "conflict" to resolve and we can get this merged. 😅

**Comment by Dan-M** [comment]
Conflicts are resolved and `reactivestreams.md` is using mdoc as well now.
Regarding the warnings - these are actually introduced by this PR:

There is 24 warnings related to link checks - (*.html / *.md):
```
warning: datatypes/index.md:12:5: Unknown link 'datatypes/fiber.html'.
- **[Fiber](fiber.html)** — A fiber value models an `IO` value that has started running, and is the moral equivalent of a green thread.
    ^^^^^^^^^^^^^^^^^^^
```

The only other warning is this one, which is probably not really relevant:
```
warning: /Users/dani/git-repos/scalaz-zio/microsite/src/main/tut/overview/testing_effects.md:113:1: Generated class repl.Session$App$database$ differs only in case from repl.Session$App$Database$.
  Such classes will overwrite one another on case-insensitive filesystems.
object database {
^
```

**Comment by jdegoes** [comment]
@Dan-M Is there some way to specify the link such that the warning goes away?

As for the object warning, we could rename that to `db` to get rid of it.

**Comment by Dan-M** [comment]
Will check if I can find a way to get rid of the warnings tomorrow morning.

**Comment by jdegoes** [comment]
@Dan-M Thank you for your hard work on this!

**Comment by Dan-M** [comment]
Warnings are fixed now as well. For the links I disabled the checks that mdoc does:
`mdocExtraArguments := List("--no-link-hygiene")`

**Comment by Dan-M** [comment]
Not sure what went wrong with the Travis build here.

**Comment by jdegoes** [comment]
@Dan-M Awesome. Thank you for your work on this huge pull request, and congratulations on becoming a ZIO contributor!

giphy

**Comment by Dan-M** [comment]
Great. Thanks for helping me get this merged.

**Pull request merged**
