### PR TITLE
V2: Make ZIO microsite look really nice scalaz#220

### PR DESCRIPTION
**Pull request by Vilkina**

### CODE REVIEW

**Comment by NeQuissimus** [comment]
@Vilkina Could you post a screenshot of what this looks like, so people won't have to build the PR? :)

**Comment by Vilkina** [comment]
@NeQuissimus , you can see the screenshot by following this link https://pbs.twimg.com/media/DracK4AWkAEhDjH.jpg:large

**Comment by Vilkina** [comment]
@NeQuissimus , how can I restart Travis?

**Comment by NeQuissimus** [comment]
Only project members can.

I have no idea why the build consistently times out now...
It happens on `master` as well.

@jdegoes ?

**Comment by jdegoes** [comment]
@NeQuissimus Does it time out at the end, or during tests?

**Comment by NeQuissimus** [comment]
Right after the tests, there is no output for > 10 minutes and then Travis considers the build stalled.

**Comment by Vilkina** [comment]
I need to do PR to another issue. Should I create another branch or I have to merge this PR, and than create PR for another issue?

**Comment by jdegoes** [comment]
giphy

**Pull request merged**
