### PR TITLE
refactored RTS for jvm into CommonRTS

### PR DESCRIPTION
**Pull request by scalavision**
Refactored out RTS from jvm into a CommonRTS in shared. Made the functions not supported by ScalaJS abstract. The code will throw exception on any `sync` operation in JS, because we are not able to block. Other things missing in ScalaJS:

* No WeakHashmap, so made an abstract method getMap in CommonRTS. Hope this will not make impact on performance. There is an implementation in ScalaNative, might be ported to ScalaJS in the future?
* The `wait()` method on AtomicReference (and probably others) would have made a linking exception. This is probably avoided due to code elimination done by the ScalaJS compiler?

Suggest that improvements on the RTS in JS should be done in a later PR. This PR is mostly about refactoring out common properties. 

I am not that familiar with the inner workings on RTS, so might be somethings that I missed. I've barely tested this in a browser, but it did work out :-)

Also, since we are not able to block, I've not found a way to run tests for JS yet.

### CODE REVIEW

**Comment by jdegoes** [comment]
@scalavision Thank you for your work on this and apologies for the delay! I'll do a comprehensive review shortly.

**Comment by scalavision** [comment]
No worries, take your time :-) 

Fixed the merge conflicts.

**Comment by jdegoes** [comment]
@scalavision This looks great to me. However, due to the large amount of code being moved around, and the new updates that have slid in, I think this is very much out of date and it will be hard to reconcile.

Do you think there is a way we can do this more incrementally? Maybe one PR to introduce some stubs, and then another one that creates a derived class to override the stubs for Javascript? Then after all that's in, we can reorganize the code like you've done here in a more logical fashion.

I'd really like to get this in, in the next couple of weeks and would be happy to assist you moving this forward.

**Comment by jdegoes** [comment]
Closing in favor of #515, which was able to happen fast enough to get merge ready!

Thanks for all your work on this @scalavision. It helped light the way for #515!

**Comment by scalavision** [comment]
Thank you for your kind words!! Sorry I was not able to complete. I hope to get more time approaching March when my current project is finished. Hope to be able to contribute then :-)

**Pull request closed without merging**
