### PR TITLE
Simplify name for IOApp, IOQueue and IORef

### LINKED ISSUE #114: Simplify and unify naming conventions
We have inconsistent naming conventions, and somewhat redundant given everything is scoped to the `zio` package. Since we are quickly approaching 1.0 of the library, we should make all changes now before the names are locked in for some time.

 * `IOApp` => `App`
 * `IOQueue` => `Queue`
 * `IORef` => `Ref`

Opportunities for other clear wins should also be investigated.

### PR DESCRIPTION
**Pull request by tuleism**
Fixes #114.

### CODE REVIEW

**Comment by jdegoes** [comment]
@tuleism Looks great, thank you! Can you resolve the conflicts?

**Comment by tuleism** [comment]
Done!

**Comment by jdegoes** [comment]
@tuleism One more minor conflict. Sorry for the rash of PRs being merged!

**Comment by tuleism** [comment]
Done :smirk_cat:

**Comment by jdegoes** [comment]
@tuleism Looks great. Thank you! 😄

**Pull request merged**
