### PR TITLE
Schedule.jittered(min, max) fixed range

### LINKED ISSUE #217: Schedule.jittered(min, max) can go above max
The formula is ` d * min + d * max * random`, instead of _e.g._`d * min * (1 - random)  + d * max * random`. It ranges from min to min + max. 

I can send a PR but it seems overkill here.

### PR DESCRIPTION
**Pull request by nicodelpiano**
Fixes #217 

If we use a more compact expression like `d * (min + random * (max - min))`, for the case where `min = Double.MinValue` and `max = Double.MaxValue` we will get `Infinity` or `NaN` depending on the value of `random`.

Do we need to write some tests for this?

### CODE REVIEW

**Comment by jdegoes** [comment]
@nicodelpiano This looks great (w/ the added test), can you update with master?

**Comment by nicodelpiano** [comment]
Hi @jdegoes @ktonga I just added a test for the `jittered` method. I've been trying to figure out how to test the functionality of `jittered`, as it modifies the duration by a random factor. What I've come up is that, for the standard jittered, i.e., `min=0.0` and `max=1.0`, it shouldn't exceed the duration specified in the initial schedule according to the new expression. Let me know your thoughts on that.

Do we need to test the correctness of the expression `d * min * (1 - random) + d * max * random`? For example, that the factor falls between `min` and `max`. If so, do we put it in `RetrySpec`?

Also, any guidance on how to do the same thing for the methods from the `Schedule` trait for #197 will be really appreciated.

Thanks!

**Comment by jdegoes** [comment]
@nicodelpiano The existing tests for `Retry` did not wait any duration, they just collected all the timings, together with the output values, and tested that. I think this is reasonable. For randomness, you can test it approximately falls within the expected output range.

**Comment by jdegoes** [comment]
@nicodelpiano The build [failed](
https://travis-ci.org/scalaz/scalaz-zio/builds/421354076?utm_source=github_status&utm_medium=notification), otherwise looks great!

**Comment by nicodelpiano** [comment]
@jdegoes Build passed :smiley:

**Comment by jdegoes** [comment]
@nicodelpiano Congrats on joining the _ZIO contributors_. Hope for more pull requests. 🙏 😄

**Pull request merged**
