### PR TITLE
WIP #651 Initial pass

### PR DESCRIPTION
**Pull request by Cereopsis**
I guess remaining questions are things like naming e.g IOInstances2 -> ZIOInstances2? I suppose there's a fair bit of private stuff in scala72.scala which wouldn't matter either way.

### CODE REVIEW

**Comment by jdegoes** [comment]
@Cereopsis This is looking really good! I would personally rename the `IO*` classes to `ZIO*`, and the `io*` instances to `zio*`.

**Comment by Cereopsis** [comment]
@degoes Makes total sense, will get into that later

**Comment by jdegoes** [comment]
@Cereopsis Is this good to merge?

**Comment by Cereopsis** [comment]
@jdegoes OK, good to go

**Comment by jdegoes** [comment]
@Cereopsis Nice work! We still need a few more instances in there (Profunctor, et al), but this is a huge improvement!

giphy

**Pull request merged**
