### PR TITLE
Feature/sonatype publishing

### PR DESCRIPTION
**Pull request by pshirshov**
For #172 
1. In case of tagged build we invoke publishSigned
2. In case of usual build we invoke publish
3. In case of tagged build we invoke `sonatypeRelease` at the end

### CODE REVIEW

**Comment by NeQuissimus** [comment]
All non-SNAPSHOT versions need to be signed, not just tags. Sonatype considers 0.1.0-<HASH> a regular version, so will require us signing those.

**Comment by pshirshov** [comment]
From my point of view (and it's a de-facto standard process) you should sing&publish tagged releases only.

Otherwise you will inevitably get into the situations when you have the same version defined in several different commits and failures because of "write-once" Central policy.

**Comment by NeQuissimus** [comment]
I don't disagree but Sonatype does.
For as long as we use hash commit versions, we need to sign them, otherwise you cannot successfully call `sbt sonatypeRelease`

**Comment by pshirshov** [comment]
I wouldn't use hash versions, but okay. So, what about now?

**Comment by jdegoes** [comment]
@NeQuissimus Is this good to merge now?

**Comment by NeQuissimus** [comment]
No, we need `publishSigned` and `sonatypeRelease` for every build.
If you don't release published builds, they are stuck in the Sonatype staging repos.

**Comment by pshirshov** [comment]
> No, we need publishSigned and sonatypeRelease for every build.
Done.

Also I've published zio to my own prefix so now all the settings are confirmed to be working.

You have to update the build to provide the following variables:
```
export SONATYPE_USERNAME=sonatype@login.tld
export SONATYPE_PASSWORD=XXXXX
export PGP_SECRING=/path/to/.secrets/gnupg/secring.gpg
export PGP_PUBRING=/path/to/.secrets/gnupg/pubring.gpg
export PGP_PASSPHRASE=XXXX
```

Those who are eager to use zio as is may pull this artifact: https://oss.sonatype.org/content/repositories/releases/com/github/pshirshov/izumi/r2/scalaz-zio_2.12/

**Comment by NeQuissimus** [comment]
The *RING variables can be static, the key can be attached to the project. Only the PASSPHRASE needs to be added to the `travis.yml`. And then it should be clean, yes.
I will need the pass phrase, so I can encrypt it into the Travis config.

**Comment by pshirshov** [comment]
> The *RING variables can be static

They can but in that case it would be invonvenient to do local deployments like I do RN under my prefix. So, please keep them configurable.

**Comment by kaishh** [comment]
@NeQuissimus 

Hi, the default values are already static: "secring.gpg"/ "pubring.gpg"

**Comment by jdegoes** [comment]
@pshirshov Sadly this [broke the build](
https://travis-ci.org/scalaz/scalaz-zio/builds/416383971) — was there something we needed to do to make this work on master? /cc @NeQuissimus

**Pull request merged**
