### PR TITLE
Fix #171 Add .sandboxed and scalaz.zio.syntax.defects module

### LINKED ISSUE #171: Implement sandboxed method on IO class
What would you say about adding 3-way `redeem` which would allow to recover from `Terminated` state?
 
This can be easily implemented by forking with `run` and matching on `ExitResult`. At the same time it may give user a peace of mind in situations where he isn't sure if his code wouldn't terminate and wishes to recover from bad states as cheap as he can in case of using `redeem` for error recovery.

In case you like the idea I would open a P/R. 

You may find an example here: https://github.com/pshirshov/triadic-result-model/blob/master/src/main/scala/MyApp.scala#L30

### PR DESCRIPTION
**Pull request by kaishh**
I've added the `sandboxed` method that allows to use `redeem` to catch termination errors and more additional syntax for catching them. @jdegoes Please comment on the names and whether you think the additional methods should be included.

### CODE REVIEW

**Comment by jdegoes** [comment]
I would personally prefer only `sandboxed`. The reason is I understand your advanced use case, but I don't want users to be encouraged to program with a tri-state effect (there is also performance overhead with sandboxing, which is suggested correctly by the name `sandboxed`, but not by `attempt3`). If users see all these attempt3/redeem3 methods, they will think they have to use them, but instead they should just be using `syncThrowable` to import throwing code. Anyway, if you limit to just `sandboxed`, I'll merge right away, and other methods could be added as syntax on top of `sandboxed`.

I also thought that a different version of `redeem` could be useful. Let's say the error type is `Either[E1, E2]`. Then we could have `redeemLeft`, `redeemRight`, which would be generic and work with any composite error type, not just those formed by `sandboxed`. This would let you do things like `sandboxed.redeemLeft((l: List[Throwable]) => ...)`.

If you like, I can think through these cases and see if there are generic combinators that would serve similar purposes to the ones introduced here, but not encourage users to tri-state.

**Comment by kaishh** [comment]
@jdegoes 

Hi, I agree with everything you said. But there is a demand for these or similar combinators in my team, even though we know they should be used only in very rare cases. I've moved them `scalaz.zio.syntax.defects` package and put appropriate warnings in documentation. There is no problem in removing them from PR if that doesn't go, though.

> I also thought that a different version of redeem could be useful. Let's say the error type is Either[E1, E2]. Then we could have redeemLeft, redeemRight, which would be generic and work with any composite error type, not just those formed by sandboxed. This would let you do things like sandboxed.redeemLeft((l: List[Throwable]) => ...).

I would think of adding another module in this case, with utilities for handling Either, Coproduct, types with `Prism`'s  kind of errors. I know some people use, or at least advocate using prisms with ZIO, I'd guess they write their own handlers.

**Comment by jdegoes** [comment]
I am good with merging `sandboxed`, I think it's natural and fits with the library, but the other methods I think don't belong in this core module (even in a separate package), and they are only moderate reductions in code compared to `io.sandboxed.catchSome { case Left(t) => ...}` (for example).

If other core ZIO contributors have other opinions, now's the time to voice them.

I think there's an argument for:

```scala
def unsandbox[E, A](io: IO[Either[List[Throwable], E], A]): IO[E, A]
```

I think this lets you express some other combinations more naturally.

You could also add the following combinator:

```scala
def sandboxWith[E2, B](f: IO[List[Throwable, E], A] => IO[List[Throwable, E2], B]): IO[E2, B] = 
  IO.unsandbox(f(io.sandboxed))
```

Then some things become quite simple:

```scala
io.sandboxWith(_.catchSome { case Left(NumberFormatException :: Nil) => IO.now(0) })
```

At this point, you might not need any helpers.

**Comment by kaishh** [comment]
@jdegoes NP, I added these three (sandboxed, sandboxWith, unsandboxed) and removed the rest

**Comment by jdegoes** [comment]
Looks great! Love the documentation and tests, too. Thank you! 🙏

**Pull request merged**
