### PR TITLE
#804 Move ExitSpec from jvm to shared

### PR DESCRIPTION
**Pull request by vilu**

### CODE REVIEW

**Comment by LGLO** [comment]
Nice, thank you!
Please run `sbt fmt`. I think build failed on missing spaces near curly braces in imports.

**Comment by vilu** [comment]
Oops, missed that. I've run scalafmt and pushed.

**Comment by LGLO** [comment]
This time build failure is caused by OOM. I've restarted one job that failed.

**Comment by vilu** [comment]
Am I expected to do something more here to help this get merged or is all good?

**Comment by ghostdogpr** [comment]
@vilu the CI failed but it seems unrelated. I just relaunched the build.

**Comment by vilu** [comment]
I re-ran it a few times with no luck. I saw some discussions around what I believe is the same error as in https://github.com/scalaz/scalaz-zio/issues/855.

**Pull request merged**
