### PR TITLE
Move ZIO Interop documentation into the microsite

### PR DESCRIPTION
**Pull request by meras**
Moving interop docs to the microsite as per #201

### CODE REVIEW

**Comment by ktonga** [comment]
Something wrong with the build. Could you take a look please?

**Comment by meras** [comment]
The build for 2.11.12 timed out after the tests passed. Not sure what happened there right now, but I'll be able to have a look tomorrow.

**Comment by ktonga** [comment]
I re-triggered the build and it passes now. So merging.
Thanks a lot for your help!

**Comment by ktonga** [comment]
@meras  Not a microsite expert here, but interop docs don't seem to be anywhere.

**Comment by NeQuissimus** [comment]
I can publish this later today. I have yet to implement automatic publishing, that is correct....

**Pull request merged**
