### PR TITLE
Implement ZStream.mapError

### PR DESCRIPTION
**Pull request by mvv**

### CODE REVIEW

**Comment by iravid** [comment]
Not sold on this approach as it doesn't lead us down a path where we can handle errors in a principled/compositional way.

**Comment by mvv** [comment]
I'm not happy with implementation either, but `fold`'s signature does not leave much of a choice. I might be missing something though, suggestions are welcome.

**Comment by iravid** [comment]
See the mapError issue for a direction

**Comment by jdegoes** [comment]
I think we have to separate producer errors from consumer errors.

```scala
ZStream[-R, +ProducerError, +ConsumerError, +A]
```

like `ZQueue`. 

Then things like `mapError` on `ZStream` will operate only over `ProducerError`. That is, they will not say anything about consumer errors.

Consumer errors are those generated from effectful folding functions / sinks. We can have separate combinators for those, but we need to know the relationship between producer errors and consumer errors.

If we want to use subtyping (which is maybe the right choice???), then when running a stream, you should get the lowest common supertype between producer error and consumer error.

**Comment by jdegoes** [comment]
Will close this until we have a better plan. @mvv Thanks for your work on this, we do badly need something along these lines.

**Pull request closed without merging**
