### PR TITLE
Fix error recovery after interruptions

### LINKED ISSUE #729: Stack unwinding doest not run ZIO.Folds on recoverable errors after interruption
```scala
for {
  r <- Ref.make("NO")
  f <- IO.never.ensuring {
      (IO.unit *> IO.fail("ERR")).catchAll(r.set)
    } .fork
  x <- f.interrupt
  v <- r.get
} yield (x, v)
```
returns `(Failure(Fail("ERR")), "NO")`. If I replace `(IO.unit *> IO.fail("ERR"))` with just `IO.fail("ERR")` the result becomes `(Failure(Interrupt), "YES")`.

There are two `unwindStack`s that happen after `f` is interrupted. First is triggered by the interruption itself and returns finalizer `(IO.unit *> IO.fail("ERR")).catchAll(r.set)`, the second happens when the execution reaches `IO.fail("ERR")`. At that point `allowRecovery` is `false` (due to `state.interrupted` and `state.terminating` both being `true`), which prevents `ZIO.Fold`s on stack from firing.

Basically, `unwindStack` and `allowRecovery` misinterpret the cause of stack unwinding to be interruption, ignoring the real cause.

### PR DESCRIPTION
**Pull request by mvv**
Fixes #729

### CODE REVIEW

**Comment by jdegoes** [comment]
@mvv 

The existing `allowRecovery` function looks like this:

```scala
  @inline
  private[this] final def allowRecovery: Boolean = {
    val currentState = state.get
    !currentState.interrupted || !currentState.terminating && noInterrupt != 0
  }
```

Because the `ensuring` happens to be executed in the process of "termination", via interruption (`kill0`, which turns `terminating` to `true`), then the fact that `noInterrupt != 0` is ignored, and recovery is not allowed.

So it seems the root cause of this problem is that `terminating = true` is rather insufficient to know whether or not to allow recovery. I think I know how to fix this cleanly, I will write more tomorrow.

**Comment by mvv** [comment]
@jdegoes 
The idea of this PR is to stop consulting fiber state (which tends to latch to certain values, thus latching the criterion) for recoverability and to explicitly mark non-recoverable `Fail`s (via a variable) at the points of their generation (`kill0` for suspended fibers and the main loop with `shouldDie = true` for running fibers). Much easier to reason about, IMO. Do you see deviations from the desired behavior with this approach?

**Comment by jdegoes** [comment]
@mvv It does not cleanly rip out the old approach but layers on more information on top.

Take a look at this function again:

```scala
  @inline
  private[this] final def allowRecovery: Boolean = {
    val currentState = state.get
    !currentState.interrupted || !currentState.terminating && noInterrupt != 0
  }
```

If we change it as follows:

```scala
  @inline
  private[this] final def allowRecovery: Boolean = {
    !state.get.interrupted || noInterrupt > 0
  }
```

Then recovery will be possible inside `ensuring` or any other uninterruptible section. In fact, as I can see, this is the only use of `terminating`, which makes me wonder why it exists and what tests will break when it is removed (but maybe those tests are wrong, we'll have to see).

Further, the big insight I had yesterday was that `noInterrupt` is actually the wrong structure for what we want to do. Instead, we need this:

```scala
@volatile var interruptibleStatus : List[Boolean] = Nil
```

Then the `Uninterruptible(io)` case can change to `ChangeInterruptible(io, boolean)`, and interpretation of that case can push the boolean flag on and pop it off in the same manner that `+= 1` and `-= 1` works today (and similar to `Lock`, and `Provide`, etc.).

Then `uninterruptible` is implemented by `ChangeInterruptible(io, false)`, and `interruptible` is implemented by `ChangeInterruptible(io, true)`.

Once this is implemented, the current interruptibility status of the fiber can be determined by examining the head of the list, or if there is no head, then using `true`. If the interruptible status is true, then redeem cannot catch interruption, but if it is false, then it can. i.e. we change `allowRecovery` to:

```scala
  @inline
  private[this] final def allowRecovery: Boolean = 
    !(state.get.interrupted && interruptible)

  private[this] final def interruptible: Boolean = 
    interruptibleStatus match { case b :: _ => b; case Nil => true }
```

Then we can smoothly transition between interruptible and uninterruptible sections without losing any details and with no more code than before, maybe less.

**Comment by mvv** [comment]
@jdegoes Just a quick point: don"t we already have the stack, it would be
wasteful to have another one (and consult it on every flatMap). Wouldn't
having a boolean variable and saving/restoring it in functions pushed to
the stack by uninterruptible/interruptible be equivalent?

**Comment by regiskuckaertz** [comment]
iirc, it was added to properly unwind the stack when interruption comes from the inside (because of a defect) and indeed there are a few tests to verify that.

**Comment by mvv** [comment]
@jdegoes 
Couple more thoughts:

Why we should not use `state.get.interrupted` in `allowRecovery`. Consider this little fiber:
```scala
f <- (IO.unit *> IO.fail("foo")).catchAll(msg => sideEffect(msg)).fork
```    
Imagine that, just as the `evaluateNow` starts handling `ZIO.Fail(Fail("foo"))` (before the `unwindStack` is called), `f` gets asynchronously interrupted via `kill0`. `f` state transitions to `Executing` with `interrupted = true`. Then `unwindStack` is called, it finds the `catchAll`'s `ZIO.Fold`, but ignores it due to `interrupted = true` and `noInterrupt == 0`, emptying the `stack` and returning `null`. `evaluateNow` calls `done(Exit.halt(Fail("foo")))`, user observes `f` exit status `Failure(Fail("foo"))`, but `sideEffect` has not been executed. Confusing! I think that `FiberState.interrupted` should have one application - in `shouldDie`.

We would need a counter (or a third value in addition to `true` and `false`) with `interruptible` to prevent `foo` from being interruptible in
```scala
uninterruptible(uninterruptible(foo.interruptible))
```
Otherwise introducing `with InsideInderruptible` in environment is pointless.

**Comment by jdegoes** [comment]
Catch all cannot stop interruption, and this is by design. I will try to mock up what I jave in mind today and show it to you.

**Comment by jdegoes** [comment]
@regiskuckaertz

I will think about this more. We already allow "sandboxing" defects in ordinary code, I think that should apply to uninterruptible code too; and moreover, I think uninterruptible code should be able to catch interruption, at least temporarily until the region exits.

**Comment by mvv** [comment]
@jdegoes 
I'm not saying it should stop interruption. The problem is that `f` terminates with `Failure(Fail("foo"))` and not with `Failure(Interrupt)`. And the overall nondetermenism of reading `state` during stack unwinding caused by a concrete `Cause`.

**Comment by mvv** [comment]
i.e. it would be much cleaner to let `catchAll` run and be interrupted.

**Comment by jdegoes** [comment]
That would be special, edge-case behavior, because interruption ordinarily does not draw distinctions between adjacent operations--it can and will interrupt anywhere. The current behavior is expected and consistent (not also, as a fiber is dying due to failure, it can acquire an interruption cause, even if it wasn't the primary failure, and this too is expected and consistent).

I think we won't need the bevahior to get what you want from `interruptible`.

**Comment by mvv** [comment]
How am I, as a user, supposed to debug that behavior? A fiber fails with `Failure(Fail("foo"))` and the error handler has not been run. How would I know that it was caused by an interruption?

**Comment by mvv** [comment]
We will go straight to `done` with the `io.cause`, no info on interruption added:
```
                  val io = curIo.asInstanceOf[ZIO.Fail[E]]

                  val finalizer = unwindStack

                  if (stack.isEmpty) {
                    // Error not caught, stack is empty:
                    if (finalizer eq null) {
                      // No finalizer, so immediately produce the error.
                      curIo = null

                      done(Exit.halt(io.cause))
                    } else {
...
```

**Comment by jdegoes** [comment]
I agree that interruption not being listed as a cause that occurs after the Fail is a bug that needs fixing ASAP (sorry, I missed that).

**Comment by jdegoes** [comment]
@mvv I mocked up what I described in #740. It fixes this issue and comes extremely close to fixing #706. I need more tests! Can you please add yours? 😄

**Comment by jdegoes** [comment]
Fixed in #740 

@mvv Thanks for your work in this and also perseverance! 😅 When it's ready (hopefully another day or so) this will be a great addition to ZIO and never would have happened without you.

**Pull request closed without merging**
