### PR TITLE
Fixed #679 - getStrLn should fail with EOFException when underlying Reader …

### LINKED ISSUE #679: Change Console.Live.getStrLn to fail with EOFException rather than returning null
The Scala `StdIn.readLine` can produce a null value which feels weird to encounter in ZIO's `Console.Live`:
https://github.com/scalaz/scalaz-zio/blob/master/core/shared/src/main/scala/scalaz/zio/console/Console.scala#L71

Should this return an Either or Option instead?

### PR DESCRIPTION
**Pull request by Cereopsis**
…returns null

I was in two minds regarding the 'purity' of the following form but erred on the side of not paying for the additional flatMap... 

```
IO.effect(SConsole.withIn(reader) {
   StdIn.readLine()
})
.flatMap {
   case s if s == null => IO.fail(new EOFException("..."))
   case s => UIO.succeed(s)
}
.refineOrDie ...
```

### CODE REVIEW

**Comment by Cereopsis** [comment]
Sorry, made a bit of a mess of the commits there. I realise it's worth doing issues on their own branch for safety

**Comment by Cereopsis** [comment]
Moved code relating to #651 onto separate branch while this is pull request is open

**Comment by jdegoes** [comment]
🙏🎉 Thanks for your work on this!

**Comment by Cereopsis** [comment]
@jdegoes The pleasure was all mine :-) 

I realise I've got a bit of a git deficiency I'll need to address in the future

**Pull request merged**
