### PR TITLE
update fs2 and AkkaStream versions for benchmarks

### PR DESCRIPTION
**Pull request by lemastero**
* update fs2 and akka-stream dependency for benchmarks
* add sbt-updates plugin it shows available updates: 
`sbt dependencyUpdates` (https://github.com/rtimush/sbt-updates)

### CODE REVIEW

**Comment by hepin1989** [comment]
Thanks, but doesn't scala-strew work here?

**Comment by lemastero** [comment]
I don't quiet follow. What/who is scala-strew? Can you provide link that I can educate myself?

I am assessing streaming and IO abstractions. (Results from different benchmarks, including RreactiveX.RxJava: https://github.com/monix/streaming-benchmarks/pull/1)

Results from this branch:

Stream Benchmarks

```
sbt "benchmarks/jmh:run -i 10 -wi 10 -f 2 -t 1 scalaz.zio.StreamBenchmarks"
```

|                                | Score  |  Error  |  Unit |
|----------|-----------|---------|-------|
|akka        |  0.209 | ± 0.009 | ops/s |
|scalazChunk | 2.105  | ± 0.056 | ops/s |
|scalaz      | 2.357  | ± 0.093 | ops/s |
|fs2         |  0.995 | ± 0.017 | ops/s |

IONarrowFlatMapBenchmark

```
sbt "benchmarks/jmh:run -i 10 -wi 10 -f 2 -t 1 scalaz.zio.IONarrowFlatMapBenchmark"
```

|         | Score          | Error         |  Unit |
|---------|----------------| ---: |-------|
| cats    |       4496.824 | ±      92.600 | ops/s |
| future  |        20.441  | ±       1.702 | ops/s |
| monix   |      5030.136  | ±      97.790 | ops/s |
| scalaz  |      3498.570  | ±      43.505 | ops/s |
| thunk   | 387862326.601  | ± 6949165.381 | ops/s |

Fastest way to run banchmars for future releases of Monix, fs2 would be to run:
`sbt dependencyUpdates` update build.sbt and run benchmarks. So I thought it could be helpful to make PR :)

**Comment by hepin1989** [comment]
Sorry，It's a robot, you can find it in the pr queue

**Comment by lemastero** [comment]
scala-strew is probably https://github.com/scala-steward
There are already PR's witch such chagnes:
- akka-stream - https://github.com/scalaz/scalaz-zio/pull/495
- fs2-core - https://github.com/scalaz/scalaz-zio/pull/492

Closing this one.

**Pull request closed without merging**
