### PR TITLE
Improve microsite #417

### PR DESCRIPTION
**Pull request by Vilkina**
Screen Shot 2019-03-19 at 3 22 30 PM
screencapture-127-0-0-1-4000-scalaz-zio-usecases-concurrency-html-2019-03-19-15_23_52

### CODE REVIEW

**Comment by Vilkina** [comment]
@NeQuissimus, I did the second commit in this PR accidentally. Is it possibly move it into another PR? :)

**Comment by jdegoes** [comment]
This has conflicts, I'd love to separate the two changes into two separate pull requests. Please open if you'd like to push this through!

**Comment by Vilkina** [comment]
Ok, I’ll do it later.

26 марта 2019, 15:17:18, от "Oleksandra Vilkina" <aleksandrag@ukr.net>:

This has conflicts, I'd love to separate the two changes into two separate pull requests. Please open if you'd like to push this through!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



--
Best regards,

Oleksandra

**Comment by jdegoes** [comment]
Happy to help with that or pull in someone else to help, just let me know.

**Comment by Vilkina** [comment]
I'm working on slides right now. Couple days left and I'm changing my talk. So I can continue to work on this when the presentation is done.

26 марта 2019, 18:00:17, от "John A. De Goes" <notifications@github.com>:

Happy to help with that or pull in someone else to help, just let me know.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



--
Best regards,

Oleksandra

**Pull request closed without merging**
