### PR TITLE
[#533] moved ClockSpec into separate module

### PR DESCRIPTION
**Pull request by vitaliihonta**

### CODE REVIEW

**Comment by jozic** [comment]
this probably deserves a section in docs, saying something like, "oh and if you want to test your ZIO code that uses Clock use this module like that ... [some examples go here]"

**Comment by NeQuissimus** [comment]
Why would the `TestClock` not live in `src/main/scala` and the spec in `src/test/scala`? Then you would publish the standard artifact without the specs inside.

**Comment by NeQuissimus** [comment]
@jdegoes My comment that I don't think this sort of stuff should live directly in ZIO but may be useful to users. So we should publish these testing helpers.

**Comment by vitaliihonta** [comment]
@NeQuissimus @jdegoes I thought that having separate dependency (like Akka testkit) would be better option. But I can move it into core if you wish

**Comment by NeQuissimus** [comment]
I like this

**Comment by vitaliihonta** [comment]
@NeQuissimus so I need to move TestClock into src/main and leave spec in src/test, right ?)

**Comment by NeQuissimus** [comment]
Please :)

**Comment by vitaliihonta** [comment]
I'll do it ASAP

**Comment by vitaliihonta** [comment]
It looks like the travis build hangs. Can anybody restart it?

**Comment by NeQuissimus** [comment]
It's because the changes cannot be merged into master. Can you rebase?

**Comment by vitaliihonta** [comment]
It's something wrong with sbt-jmh dependency for 2.11. Can anybody check or re-run?

**Pull request merged**
