### PR TITLE
Add stack-safety test for deep flatMap.

### PR DESCRIPTION
**Pull request by hepin1989**

### CODE REVIEW

**Comment by jdegoes** [comment]
@hepin1989 This test looks like it could take a long time to run. I'm hesitant to merge it because of that (also many other tests would blow up if ZIO weren't stack safe).

**Comment by hepin1989** [comment]
image
@jdegoes another 60 seconds:) 
But Monix used this as an example of stack safe, so I think it would be nice to be included in as a test.

**Comment by jdegoes** [comment]
@hepin1989 Can we decrease the number so it adds only 10 seconds?

**Comment by hepin1989** [comment]
@jdegoes I have decreased that to 1000.

**Pull request merged**
